services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1    # 1 = Latest stable
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"                  # <Host Port>:<Container Port>
    restart: always
