services:
  twingate_connector:
    container_name: twingate
    restart: always
    image: twingate/connector:latest
    environment:
      - TWINGATE_NETWORK=homelab   #Name of your Twingate network
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LOG_ANALYTICS=v2
      - TWINGATE_LOG_LEVEL=3
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
