---
services:
  portainer:
    image: portainer/portainer-ee:2.27.9
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000 # for http
    volumes:
      - /home/administrator/portainer/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.yourdomain.com`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.local.yourdomain.com`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"
      # Edge | Portainer Edge Agent
      - "traefik.http.routers.edge.entrypoints=http"
      - "traefik.http.routers.edge.rule=Host(`portainer-edge.local.yourdomain.com`)"
      - "traefik.http.middlewares.edge-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.edge.middlewares=edge-https-redirect"
      - "traefik.http.routers.edge-secure.entrypoints=https"
      - "traefik.http.routers.edge-secure.rule=Host(`portainer-edge.local.yourdomain.com`)"
      - "traefik.http.routers.edge-secure.tls=true"
      - "traefik.http.routers.edge-secure.service=edge"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
